PRODUCT_PACKAGES += libespeak
MY_SOURCE = external/espeak/espeak-data
MY_TARGET = /system/tts/espeak-data

PRODUCT_COPY_FILES += \
  $(MY_SOURCE)/intonations:$(MY_TARGET)/intonations \
  $(MY_SOURCE)/zhy_dict:$(MY_TARGET)/zhy_dict \
  $(MY_SOURCE)/lv_dict:$(MY_TARGET)/lv_dict \
  $(MY_SOURCE)/ml_dict:$(MY_TARGET)/ml_dict \
  $(MY_SOURCE)/da_dict:$(MY_TARGET)/da_dict \
  $(MY_SOURCE)/pl_dict:$(MY_TARGET)/pl_dict \
  $(MY_SOURCE)/fa_dict:$(MY_TARGET)/fa_dict \
  $(MY_SOURCE)/ca_dict:$(MY_TARGET)/ca_dict \
  $(MY_SOURCE)/ro_dict:$(MY_TARGET)/ro_dict \
  $(MY_SOURCE)/sq_dict:$(MY_TARGET)/sq_dict \
  $(MY_SOURCE)/sk_dict:$(MY_TARGET)/sk_dict \
  $(MY_SOURCE)/fr_dict:$(MY_TARGET)/fr_dict \
  $(MY_SOURCE)/mk_dict:$(MY_TARGET)/mk_dict \
  $(MY_SOURCE)/bg_dict:$(MY_TARGET)/bg_dict \
  $(MY_SOURCE)/lt_dict:$(MY_TARGET)/lt_dict \
  $(MY_SOURCE)/te_dict:$(MY_TARGET)/te_dict \
  $(MY_SOURCE)/el_dict:$(MY_TARGET)/el_dict \
  $(MY_SOURCE)/is_dict:$(MY_TARGET)/is_dict \
  $(MY_SOURCE)/hi_dict:$(MY_TARGET)/hi_dict \
  $(MY_SOURCE)/ta_dict:$(MY_TARGET)/ta_dict \
  $(MY_SOURCE)/hbs_dict:$(MY_TARGET)/hbs_dict \
  $(MY_SOURCE)/jbo_dict:$(MY_TARGET)/jbo_dict \
  $(MY_SOURCE)/nl_dict:$(MY_TARGET)/nl_dict \
  $(MY_SOURCE)/ru_dict:$(MY_TARGET)/ru_dict \
  $(MY_SOURCE)/ka_dict:$(MY_TARGET)/ka_dict \
  $(MY_SOURCE)/de_dict:$(MY_TARGET)/de_dict \
  $(MY_SOURCE)/pt_dict:$(MY_TARGET)/pt_dict \
  $(MY_SOURCE)/sv_dict:$(MY_TARGET)/sv_dict \
  $(MY_SOURCE)/voices/en:$(MY_TARGET)/voices/en \
  $(MY_SOURCE)/voices/europe/no:$(MY_TARGET)/voices/europe/no \
  $(MY_SOURCE)/voices/europe/cy:$(MY_TARGET)/voices/europe/cy \
  $(MY_SOURCE)/voices/europe/eu:$(MY_TARGET)/voices/europe/eu \
  $(MY_SOURCE)/voices/europe/sv:$(MY_TARGET)/voices/europe/sv \
  $(MY_SOURCE)/voices/europe/bs:$(MY_TARGET)/voices/europe/bs \
  $(MY_SOURCE)/voices/europe/bg:$(MY_TARGET)/voices/europe/bg \
  $(MY_SOURCE)/voices/europe/mk:$(MY_TARGET)/voices/europe/mk \
  $(MY_SOURCE)/voices/europe/hr:$(MY_TARGET)/voices/europe/hr \
  $(MY_SOURCE)/voices/europe/sk:$(MY_TARGET)/voices/europe/sk \
  $(MY_SOURCE)/voices/europe/sr:$(MY_TARGET)/voices/europe/sr \
  $(MY_SOURCE)/voices/europe/ga:$(MY_TARGET)/voices/europe/ga \
  $(MY_SOURCE)/voices/europe/sq:$(MY_TARGET)/voices/europe/sq \
  $(MY_SOURCE)/voices/europe/da:$(MY_TARGET)/voices/europe/da \
  $(MY_SOURCE)/voices/europe/es:$(MY_TARGET)/voices/europe/es \
  $(MY_SOURCE)/voices/europe/lv:$(MY_TARGET)/voices/europe/lv \
  $(MY_SOURCE)/voices/europe/nl:$(MY_TARGET)/voices/europe/nl \
  $(MY_SOURCE)/voices/europe/lt:$(MY_TARGET)/voices/europe/lt \
  $(MY_SOURCE)/voices/europe/hu:$(MY_TARGET)/voices/europe/hu \
  $(MY_SOURCE)/voices/europe/is:$(MY_TARGET)/voices/europe/is \
  $(MY_SOURCE)/voices/europe/cs:$(MY_TARGET)/voices/europe/cs \
  $(MY_SOURCE)/voices/europe/fr-be:$(MY_TARGET)/voices/europe/fr-be \
  $(MY_SOURCE)/voices/europe/pl:$(MY_TARGET)/voices/europe/pl \
  $(MY_SOURCE)/voices/europe/ro:$(MY_TARGET)/voices/europe/ro \
  $(MY_SOURCE)/voices/europe/et:$(MY_TARGET)/voices/europe/et \
  $(MY_SOURCE)/voices/europe/fi:$(MY_TARGET)/voices/europe/fi \
  $(MY_SOURCE)/voices/europe/ca:$(MY_TARGET)/voices/europe/ca \
  $(MY_SOURCE)/voices/europe/el:$(MY_TARGET)/voices/europe/el \
  $(MY_SOURCE)/voices/europe/an:$(MY_TARGET)/voices/europe/an \
  $(MY_SOURCE)/voices/europe/pt-pt:$(MY_TARGET)/voices/europe/pt-pt \
  $(MY_SOURCE)/voices/europe/ru:$(MY_TARGET)/voices/europe/ru \
  $(MY_SOURCE)/voices/europe/it:$(MY_TARGET)/voices/europe/it \
  $(MY_SOURCE)/voices/de:$(MY_TARGET)/voices/de \
  $(MY_SOURCE)/voices/fr:$(MY_TARGET)/voices/fr \
  $(MY_SOURCE)/voices/other/en-wm:$(MY_TARGET)/voices/other/en-wm \
  $(MY_SOURCE)/voices/other/grc:$(MY_TARGET)/voices/other/grc \
  $(MY_SOURCE)/voices/other/en-rp:$(MY_TARGET)/voices/other/en-rp \
  $(MY_SOURCE)/voices/other/sw:$(MY_TARGET)/voices/other/sw \
  $(MY_SOURCE)/voices/other/la:$(MY_TARGET)/voices/other/la \
  $(MY_SOURCE)/voices/other/jbo:$(MY_TARGET)/voices/other/jbo \
  $(MY_SOURCE)/voices/other/en-wi:$(MY_TARGET)/voices/other/en-wi \
  $(MY_SOURCE)/voices/other/af:$(MY_TARGET)/voices/other/af \
  $(MY_SOURCE)/voices/other/en-n:$(MY_TARGET)/voices/other/en-n \
  $(MY_SOURCE)/voices/other/lfn:$(MY_TARGET)/voices/other/lfn \
  $(MY_SOURCE)/voices/other/en-sc:$(MY_TARGET)/voices/other/en-sc \
  $(MY_SOURCE)/voices/other/eo:$(MY_TARGET)/voices/other/eo \
  $(MY_SOURCE)/voices/asia/hi:$(MY_TARGET)/voices/asia/hi \
  $(MY_SOURCE)/voices/asia/gu:$(MY_TARGET)/voices/asia/gu \
  $(MY_SOURCE)/voices/asia/vi-hue:$(MY_TARGET)/voices/asia/vi-hue \
  $(MY_SOURCE)/voices/asia/pa:$(MY_TARGET)/voices/asia/pa \
  $(MY_SOURCE)/voices/asia/zh-yue:$(MY_TARGET)/voices/asia/zh-yue \
  $(MY_SOURCE)/voices/asia/ml:$(MY_TARGET)/voices/asia/ml \
  $(MY_SOURCE)/voices/asia/vi-sgn:$(MY_TARGET)/voices/asia/vi-sgn \
  $(MY_SOURCE)/voices/asia/zh:$(MY_TARGET)/voices/asia/zh \
  $(MY_SOURCE)/voices/asia/hy-west:$(MY_TARGET)/voices/asia/hy-west \
  $(MY_SOURCE)/voices/asia/hy:$(MY_TARGET)/voices/asia/hy \
  $(MY_SOURCE)/voices/asia/fa-pin:$(MY_TARGET)/voices/asia/fa-pin \
  $(MY_SOURCE)/voices/asia/vi:$(MY_TARGET)/voices/asia/vi \
  $(MY_SOURCE)/voices/asia/ne:$(MY_TARGET)/voices/asia/ne \
  $(MY_SOURCE)/voices/asia/kn:$(MY_TARGET)/voices/asia/kn \
  $(MY_SOURCE)/voices/asia/ku:$(MY_TARGET)/voices/asia/ku \
  $(MY_SOURCE)/voices/asia/fa:$(MY_TARGET)/voices/asia/fa \
  $(MY_SOURCE)/voices/asia/fa-en-us:$(MY_TARGET)/voices/asia/fa-en-us \
  $(MY_SOURCE)/voices/asia/bn:$(MY_TARGET)/voices/asia/bn \
  $(MY_SOURCE)/voices/asia/id:$(MY_TARGET)/voices/asia/id \
  $(MY_SOURCE)/voices/asia/ta:$(MY_TARGET)/voices/asia/ta \
  $(MY_SOURCE)/voices/asia/ka:$(MY_TARGET)/voices/asia/ka \
  $(MY_SOURCE)/voices/asia/te:$(MY_TARGET)/voices/asia/te \
  $(MY_SOURCE)/voices/asia/ko:$(MY_TARGET)/voices/asia/ko \
  $(MY_SOURCE)/voices/asia/ms:$(MY_TARGET)/voices/asia/ms \
  $(MY_SOURCE)/voices/asia/tr:$(MY_TARGET)/voices/asia/tr \
  $(MY_SOURCE)/voices/pt:$(MY_TARGET)/voices/pt \
  $(MY_SOURCE)/voices/es-la:$(MY_TARGET)/voices/es-la \
  $(MY_SOURCE)/voices/!v/klatt4:$(MY_TARGET)/voices/!v/klatt4 \
  $(MY_SOURCE)/voices/!v/m2:$(MY_TARGET)/voices/!v/m2 \
  $(MY_SOURCE)/voices/!v/croak:$(MY_TARGET)/voices/!v/croak \
  $(MY_SOURCE)/voices/!v/klatt:$(MY_TARGET)/voices/!v/klatt \
  $(MY_SOURCE)/voices/!v/f3:$(MY_TARGET)/voices/!v/f3 \
  $(MY_SOURCE)/voices/!v/m6:$(MY_TARGET)/voices/!v/m6 \
  $(MY_SOURCE)/voices/!v/m7:$(MY_TARGET)/voices/!v/m7 \
  $(MY_SOURCE)/voices/!v/whisperf:$(MY_TARGET)/voices/!v/whisperf \
  $(MY_SOURCE)/voices/!v/klatt3:$(MY_TARGET)/voices/!v/klatt3 \
  $(MY_SOURCE)/voices/!v/f4:$(MY_TARGET)/voices/!v/f4 \
  $(MY_SOURCE)/voices/!v/m4:$(MY_TARGET)/voices/!v/m4 \
  $(MY_SOURCE)/voices/!v/f1:$(MY_TARGET)/voices/!v/f1 \
  $(MY_SOURCE)/voices/!v/f2:$(MY_TARGET)/voices/!v/f2 \
  $(MY_SOURCE)/voices/!v/klatt2:$(MY_TARGET)/voices/!v/klatt2 \
  $(MY_SOURCE)/voices/!v/m3:$(MY_TARGET)/voices/!v/m3 \
  $(MY_SOURCE)/voices/!v/m1:$(MY_TARGET)/voices/!v/m1 \
  $(MY_SOURCE)/voices/!v/f5:$(MY_TARGET)/voices/!v/f5 \
  $(MY_SOURCE)/voices/!v/whisper:$(MY_TARGET)/voices/!v/whisper \
  $(MY_SOURCE)/voices/!v/m5:$(MY_TARGET)/voices/!v/m5 \
  $(MY_SOURCE)/voices/default:$(MY_TARGET)/voices/default \
  $(MY_SOURCE)/voices/en-us:$(MY_TARGET)/voices/en-us \
  $(MY_SOURCE)/ku_dict:$(MY_TARGET)/ku_dict \
  $(MY_SOURCE)/an_dict:$(MY_TARGET)/an_dict \
  $(MY_SOURCE)/bn_dict:$(MY_TARGET)/bn_dict \
  $(MY_SOURCE)/sw_dict:$(MY_TARGET)/sw_dict \
  $(MY_SOURCE)/grc_dict:$(MY_TARGET)/grc_dict \
  $(MY_SOURCE)/pa_dict:$(MY_TARGET)/pa_dict \
  $(MY_SOURCE)/no_dict:$(MY_TARGET)/no_dict \
  $(MY_SOURCE)/id_dict:$(MY_TARGET)/id_dict \
  $(MY_SOURCE)/cy_dict:$(MY_TARGET)/cy_dict \
  $(MY_SOURCE)/eu_dict:$(MY_TARGET)/eu_dict \
  $(MY_SOURCE)/es_dict:$(MY_TARGET)/es_dict \
  $(MY_SOURCE)/vi_dict:$(MY_TARGET)/vi_dict \
  $(MY_SOURCE)/phontab:$(MY_TARGET)/phontab \
  $(MY_SOURCE)/phondata:$(MY_TARGET)/phondata \
  $(MY_SOURCE)/hy_dict:$(MY_TARGET)/hy_dict \
  $(MY_SOURCE)/it_dict:$(MY_TARGET)/it_dict \
  $(MY_SOURCE)/ms_dict:$(MY_TARGET)/ms_dict \
  $(MY_SOURCE)/tr_dict:$(MY_TARGET)/tr_dict \
  $(MY_SOURCE)/en_dict:$(MY_TARGET)/en_dict \
  $(MY_SOURCE)/eo_dict:$(MY_TARGET)/eo_dict \
  $(MY_SOURCE)/phonindex:$(MY_TARGET)/phonindex \
  $(MY_SOURCE)/et_dict:$(MY_TARGET)/et_dict \
  $(MY_SOURCE)/zh_dict:$(MY_TARGET)/zh_dict \
  $(MY_SOURCE)/phondata-manifest:$(MY_TARGET)/phondata-manifest \
  $(MY_SOURCE)/af_dict:$(MY_TARGET)/af_dict \
  $(MY_SOURCE)/kn_dict:$(MY_TARGET)/kn_dict \
  $(MY_SOURCE)/ko_dict:$(MY_TARGET)/ko_dict \
  $(MY_SOURCE)/cs_dict:$(MY_TARGET)/cs_dict \
  $(MY_SOURCE)/fi_dict:$(MY_TARGET)/fi_dict \
  $(MY_SOURCE)/gu_dict:$(MY_TARGET)/gu_dict \
  $(MY_SOURCE)/ne_dict:$(MY_TARGET)/ne_dict \
  $(MY_SOURCE)/ga_dict:$(MY_TARGET)/ga_dict \
  $(MY_SOURCE)/la_dict:$(MY_TARGET)/la_dict \
  $(MY_SOURCE)/hu_dict:$(MY_TARGET)/hu_dict
