PRODUCT_PACKAGES += libespeak

PRODUCT_COPY_FILES += \
  external/espeak/espeak-data/voices/mb/mb-de4-en:/system/tts/espeak-data/voices/mb/mb-de4-en \
  external/espeak/espeak-data/voices/mb/mb-br3:/system/tts/espeak-data/voices/mb/mb-br3 \
  external/espeak/espeak-data/voices/mb/mb-hu1-en:/system/tts/espeak-data/voices/mb/mb-hu1-en \
  external/espeak/espeak-data/voices/mb/mb-us3:/system/tts/espeak-data/voices/mb/mb-us3 \
  external/espeak/espeak-data/voices/mb/mb-it4:/system/tts/espeak-data/voices/mb/mb-it4 \
  external/espeak/espeak-data/voices/mb/mb-de2:/system/tts/espeak-data/voices/mb/mb-de2 \
  external/espeak/espeak-data/voices/mb/mb-tr1:/system/tts/espeak-data/voices/mb/mb-tr1 \
  external/espeak/espeak-data/voices/mb/mb-es2:/system/tts/espeak-data/voices/mb/mb-es2 \
  external/espeak/espeak-data/voices/mb/mb-af1:/system/tts/espeak-data/voices/mb/mb-af1 \
  external/espeak/espeak-data/voices/mb/mb-sw1:/system/tts/espeak-data/voices/mb/mb-sw1 \
  external/espeak/espeak-data/voices/mb/mb-us2:/system/tts/espeak-data/voices/mb/mb-us2 \
  external/espeak/espeak-data/voices/mb/mb-de7:/system/tts/espeak-data/voices/mb/mb-de7 \
  external/espeak/espeak-data/voices/mb/mb-sw2-en:/system/tts/espeak-data/voices/mb/mb-sw2-en \
  external/espeak/espeak-data/voices/mb/mb-mx2:/system/tts/espeak-data/voices/mb/mb-mx2 \
  external/espeak/espeak-data/voices/mb/mb-en1:/system/tts/espeak-data/voices/mb/mb-en1 \
  external/espeak/espeak-data/voices/mb/mb-id1:/system/tts/espeak-data/voices/mb/mb-id1 \
  external/espeak/espeak-data/voices/mb/mb-cz2:/system/tts/espeak-data/voices/mb/mb-cz2 \
  external/espeak/espeak-data/voices/mb/mb-af1-en:/system/tts/espeak-data/voices/mb/mb-af1-en \
  external/espeak/espeak-data/voices/mb/mb-ir2:/system/tts/espeak-data/voices/mb/mb-ir2 \
  external/espeak/espeak-data/voices/mb/mb-de6-grc:/system/tts/espeak-data/voices/mb/mb-de6-grc \
  external/espeak/espeak-data/voices/mb/mb-ic1:/system/tts/espeak-data/voices/mb/mb-ic1 \
  external/espeak/espeak-data/voices/mb/mb-pt1:/system/tts/espeak-data/voices/mb/mb-pt1 \
  external/espeak/espeak-data/voices/mb/mb-ir1:/system/tts/espeak-data/voices/mb/mb-ir1 \
  external/espeak/espeak-data/voices/mb/mb-la1:/system/tts/espeak-data/voices/mb/mb-la1 \
  external/espeak/espeak-data/voices/mb/mb-gr2-en:/system/tts/espeak-data/voices/mb/mb-gr2-en \
  external/espeak/espeak-data/voices/mb/mb-sw1-en:/system/tts/espeak-data/voices/mb/mb-sw1-en \
  external/espeak/espeak-data/voices/mb/mb-cr1:/system/tts/espeak-data/voices/mb/mb-cr1 \
  external/espeak/espeak-data/voices/mb/mb-mx1:/system/tts/espeak-data/voices/mb/mb-mx1 \
  external/espeak/espeak-data/voices/mb/mb-de4:/system/tts/espeak-data/voices/mb/mb-de4 \
  external/espeak/espeak-data/voices/mb/mb-de5-en:/system/tts/espeak-data/voices/mb/mb-de5-en \
  external/espeak/espeak-data/voices/mb/mb-ro1:/system/tts/espeak-data/voices/mb/mb-ro1 \
  external/espeak/espeak-data/voices/mb/mb-fr4-en:/system/tts/espeak-data/voices/mb/mb-fr4-en \
  external/espeak/espeak-data/voices/mb/mb-fr1:/system/tts/espeak-data/voices/mb/mb-fr1 \
  external/espeak/espeak-data/voices/mb/mb-fr4:/system/tts/espeak-data/voices/mb/mb-fr4 \
  external/espeak/espeak-data/voices/mb/mb-br1:/system/tts/espeak-data/voices/mb/mb-br1 \
  external/espeak/espeak-data/voices/mb/mb-it3:/system/tts/espeak-data/voices/mb/mb-it3 \
  external/espeak/espeak-data/voices/mb/mb-vz1:/system/tts/espeak-data/voices/mb/mb-vz1 \
  external/espeak/espeak-data/voices/mb/mb-es1:/system/tts/espeak-data/voices/mb/mb-es1 \
  external/espeak/espeak-data/voices/mb/mb-nl2-en:/system/tts/espeak-data/voices/mb/mb-nl2-en \
  external/espeak/espeak-data/voices/mb/mb-de5:/system/tts/espeak-data/voices/mb/mb-de5 \
  external/espeak/espeak-data/voices/mb/mb-br4:/system/tts/espeak-data/voices/mb/mb-br4 \
  external/espeak/espeak-data/voices/mb/mb-hu1:/system/tts/espeak-data/voices/mb/mb-hu1 \
  external/espeak/espeak-data/voices/mb/mb-us1:/system/tts/espeak-data/voices/mb/mb-us1 \
  external/espeak/espeak-data/voices/mb/mb-de6:/system/tts/espeak-data/voices/mb/mb-de6 \
  external/espeak/espeak-data/voices/mb/mb-pl1:/system/tts/espeak-data/voices/mb/mb-pl1 \
  external/espeak/espeak-data/voices/mb/mb-tr2:/system/tts/espeak-data/voices/mb/mb-tr2 \
  external/espeak/espeak-data/voices/mb/mb-sw2:/system/tts/espeak-data/voices/mb/mb-sw2 \
  external/espeak/espeak-data/voices/mb/mb-ee1:/system/tts/espeak-data/voices/mb/mb-ee1 \
  external/espeak/espeak-data/voices/mb/mb-pl1-en:/system/tts/espeak-data/voices/mb/mb-pl1-en \
  external/espeak/espeak-data/voices/mb/mb-nl2:/system/tts/espeak-data/voices/mb/mb-nl2 \
  external/espeak/espeak-data/voices/mb/mb-fr1-en:/system/tts/espeak-data/voices/mb/mb-fr1-en \
  external/espeak/espeak-data/voices/mb/mb-ro1-en:/system/tts/espeak-data/voices/mb/mb-ro1-en \
  external/espeak/espeak-data/voices/mb/mb-gr2:/system/tts/espeak-data/voices/mb/mb-gr2 \
  external/espeak/espeak-data/voices/en:/system/tts/espeak-data/voices/en \
  external/espeak/espeak-data/voices/europe/no:/system/tts/espeak-data/voices/europe/no \
  external/espeak/espeak-data/voices/europe/cy:/system/tts/espeak-data/voices/europe/cy \
  external/espeak/espeak-data/voices/europe/eu:/system/tts/espeak-data/voices/europe/eu \
  external/espeak/espeak-data/voices/europe/sv:/system/tts/espeak-data/voices/europe/sv \
  external/espeak/espeak-data/voices/europe/bs:/system/tts/espeak-data/voices/europe/bs \
  external/espeak/espeak-data/voices/europe/bg:/system/tts/espeak-data/voices/europe/bg \
  external/espeak/espeak-data/voices/europe/mk:/system/tts/espeak-data/voices/europe/mk \
  external/espeak/espeak-data/voices/europe/hr:/system/tts/espeak-data/voices/europe/hr \
  external/espeak/espeak-data/voices/europe/sk:/system/tts/espeak-data/voices/europe/sk \
  external/espeak/espeak-data/voices/europe/sr:/system/tts/espeak-data/voices/europe/sr \
  external/espeak/espeak-data/voices/europe/ga:/system/tts/espeak-data/voices/europe/ga \
  external/espeak/espeak-data/voices/europe/sq:/system/tts/espeak-data/voices/europe/sq \
  external/espeak/espeak-data/voices/europe/da:/system/tts/espeak-data/voices/europe/da \
  external/espeak/espeak-data/voices/europe/es:/system/tts/espeak-data/voices/europe/es \
  external/espeak/espeak-data/voices/europe/lv:/system/tts/espeak-data/voices/europe/lv \
  external/espeak/espeak-data/voices/europe/nl:/system/tts/espeak-data/voices/europe/nl \
  external/espeak/espeak-data/voices/europe/lt:/system/tts/espeak-data/voices/europe/lt \
  external/espeak/espeak-data/voices/europe/hu:/system/tts/espeak-data/voices/europe/hu \
  external/espeak/espeak-data/voices/europe/is:/system/tts/espeak-data/voices/europe/is \
  external/espeak/espeak-data/voices/europe/cs:/system/tts/espeak-data/voices/europe/cs \
  external/espeak/espeak-data/voices/europe/fr-be:/system/tts/espeak-data/voices/europe/fr-be \
  external/espeak/espeak-data/voices/europe/pl:/system/tts/espeak-data/voices/europe/pl \
  external/espeak/espeak-data/voices/europe/ro:/system/tts/espeak-data/voices/europe/ro \
  external/espeak/espeak-data/voices/europe/et:/system/tts/espeak-data/voices/europe/et \
  external/espeak/espeak-data/voices/europe/fi:/system/tts/espeak-data/voices/europe/fi \
  external/espeak/espeak-data/voices/europe/ca:/system/tts/espeak-data/voices/europe/ca \
  external/espeak/espeak-data/voices/europe/el:/system/tts/espeak-data/voices/europe/el \
  external/espeak/espeak-data/voices/europe/an:/system/tts/espeak-data/voices/europe/an \
  external/espeak/espeak-data/voices/europe/pt-pt:/system/tts/espeak-data/voices/europe/pt-pt \
  external/espeak/espeak-data/voices/europe/ru:/system/tts/espeak-data/voices/europe/ru \
  external/espeak/espeak-data/voices/europe/it:/system/tts/espeak-data/voices/europe/it \
  external/espeak/espeak-data/voices/de:/system/tts/espeak-data/voices/de \
  external/espeak/espeak-data/voices/fr:/system/tts/espeak-data/voices/fr \
  external/espeak/espeak-data/voices/other/en-wm:/system/tts/espeak-data/voices/other/en-wm \
  external/espeak/espeak-data/voices/other/grc:/system/tts/espeak-data/voices/other/grc \
  external/espeak/espeak-data/voices/other/en-rp:/system/tts/espeak-data/voices/other/en-rp \
  external/espeak/espeak-data/voices/other/sw:/system/tts/espeak-data/voices/other/sw \
  external/espeak/espeak-data/voices/other/la:/system/tts/espeak-data/voices/other/la \
  external/espeak/espeak-data/voices/other/jbo:/system/tts/espeak-data/voices/other/jbo \
  external/espeak/espeak-data/voices/other/en-wi:/system/tts/espeak-data/voices/other/en-wi \
  external/espeak/espeak-data/voices/other/af:/system/tts/espeak-data/voices/other/af \
  external/espeak/espeak-data/voices/other/en-n:/system/tts/espeak-data/voices/other/en-n \
  external/espeak/espeak-data/voices/other/lfn:/system/tts/espeak-data/voices/other/lfn \
  external/espeak/espeak-data/voices/other/en-sc:/system/tts/espeak-data/voices/other/en-sc \
  external/espeak/espeak-data/voices/other/eo:/system/tts/espeak-data/voices/other/eo \
  external/espeak/espeak-data/voices/asia/hi:/system/tts/espeak-data/voices/asia/hi \
  external/espeak/espeak-data/voices/asia/gu:/system/tts/espeak-data/voices/asia/gu \
  external/espeak/espeak-data/voices/asia/vi-hue:/system/tts/espeak-data/voices/asia/vi-hue \
  external/espeak/espeak-data/voices/asia/pa:/system/tts/espeak-data/voices/asia/pa \
  external/espeak/espeak-data/voices/asia/zh-yue:/system/tts/espeak-data/voices/asia/zh-yue \
  external/espeak/espeak-data/voices/asia/ml:/system/tts/espeak-data/voices/asia/ml \
  external/espeak/espeak-data/voices/asia/vi-sgn:/system/tts/espeak-data/voices/asia/vi-sgn \
  external/espeak/espeak-data/voices/asia/zh:/system/tts/espeak-data/voices/asia/zh \
  external/espeak/espeak-data/voices/asia/hy-west:/system/tts/espeak-data/voices/asia/hy-west \
  external/espeak/espeak-data/voices/asia/hy:/system/tts/espeak-data/voices/asia/hy \
  external/espeak/espeak-data/voices/asia/fa-pin:/system/tts/espeak-data/voices/asia/fa-pin \
  external/espeak/espeak-data/voices/asia/vi:/system/tts/espeak-data/voices/asia/vi \
  external/espeak/espeak-data/voices/asia/ne:/system/tts/espeak-data/voices/asia/ne \
  external/espeak/espeak-data/voices/asia/kn:/system/tts/espeak-data/voices/asia/kn \
  external/espeak/espeak-data/voices/asia/ku:/system/tts/espeak-data/voices/asia/ku \
  external/espeak/espeak-data/voices/asia/fa:/system/tts/espeak-data/voices/asia/fa \
  external/espeak/espeak-data/voices/asia/fa-en-us:/system/tts/espeak-data/voices/asia/fa-en-us \
  external/espeak/espeak-data/voices/asia/bn:/system/tts/espeak-data/voices/asia/bn \
  external/espeak/espeak-data/voices/asia/id:/system/tts/espeak-data/voices/asia/id \
  external/espeak/espeak-data/voices/asia/ta:/system/tts/espeak-data/voices/asia/ta \
  external/espeak/espeak-data/voices/asia/ka:/system/tts/espeak-data/voices/asia/ka \
  external/espeak/espeak-data/voices/asia/te:/system/tts/espeak-data/voices/asia/te \
  external/espeak/espeak-data/voices/asia/ko:/system/tts/espeak-data/voices/asia/ko \
  external/espeak/espeak-data/voices/asia/ms:/system/tts/espeak-data/voices/asia/ms \
  external/espeak/espeak-data/voices/asia/tr:/system/tts/espeak-data/voices/asia/tr \
  external/espeak/espeak-data/voices/pt:/system/tts/espeak-data/voices/pt \
  external/espeak/espeak-data/voices/es-la:/system/tts/espeak-data/voices/es-la \
  external/espeak/espeak-data/voices/!v/klatt4:/system/tts/espeak-data/voices/!v/klatt4 \
  external/espeak/espeak-data/voices/!v/m2:/system/tts/espeak-data/voices/!v/m2 \
  external/espeak/espeak-data/voices/!v/croak:/system/tts/espeak-data/voices/!v/croak \
  external/espeak/espeak-data/voices/!v/klatt:/system/tts/espeak-data/voices/!v/klatt \
  external/espeak/espeak-data/voices/!v/f3:/system/tts/espeak-data/voices/!v/f3 \
  external/espeak/espeak-data/voices/!v/m6:/system/tts/espeak-data/voices/!v/m6 \
  external/espeak/espeak-data/voices/!v/m7:/system/tts/espeak-data/voices/!v/m7 \
  external/espeak/espeak-data/voices/!v/whisperf:/system/tts/espeak-data/voices/!v/whisperf \
  external/espeak/espeak-data/voices/!v/klatt3:/system/tts/espeak-data/voices/!v/klatt3 \
  external/espeak/espeak-data/voices/!v/f4:/system/tts/espeak-data/voices/!v/f4 \
  external/espeak/espeak-data/voices/!v/m4:/system/tts/espeak-data/voices/!v/m4 \
  external/espeak/espeak-data/voices/!v/f1:/system/tts/espeak-data/voices/!v/f1 \
  external/espeak/espeak-data/voices/!v/f2:/system/tts/espeak-data/voices/!v/f2 \
  external/espeak/espeak-data/voices/!v/klatt2:/system/tts/espeak-data/voices/!v/klatt2 \
  external/espeak/espeak-data/voices/!v/m3:/system/tts/espeak-data/voices/!v/m3 \
  external/espeak/espeak-data/voices/!v/m1:/system/tts/espeak-data/voices/!v/m1 \
  external/espeak/espeak-data/voices/!v/f5:/system/tts/espeak-data/voices/!v/f5 \
  external/espeak/espeak-data/voices/!v/whisper:/system/tts/espeak-data/voices/!v/whisper \
  external/espeak/espeak-data/voices/!v/m5:/system/tts/espeak-data/voices/!v/m5 \
  external/espeak/espeak-data/voices/default:/system/tts/espeak-data/voices/default \
  external/espeak/espeak-data/voices/en-us:/system/tts/espeak-data/voices/en-us